apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "kubernetes-ingress-info.fullname" . }}
  labels:
{{ include "kubernetes-ingress-info.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels: {{ include "kubernetes-ingress-info.matchLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "kubernetes-ingress-info.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: info-port
              containerPort: {{ .Values.listenPort }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | trim | nindent 12 }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | trim | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | trim | nindent 12 }}
          {{- if .Values.command }}
          command:
            {{- range .Values.command }}
            - {{ . | quote }}
            {{- end }}
          {{- end }}
          args:
            - "--load-config-mode"
            - {{ .Values.loadConfigMode | quote }}
            {{- if .Values.labelSelectorIncludes }}
            - "--include-label-selectors"
            - {{ include "joinListWithComma" .Values.labelSelectorIncludes | quote }}
            {{- end }}
            {{- if .Values.labelSelectorExcludes }}
            - "--exclude-label-selectors"
            - {{ include "joinListWithComma" .Values.labelSelectorExcludes | quote }}
            {{- end }}
            {{- if .Values.namespaceScope }}
            - "--namespace"
            - {{ include "joinListWithComma" .Values.namespaceScope | quote }}
            {{- end }}
            - "--listen-port"
            - {{ .Values.listenPort | quote }}
            {{- if .Values.hostMatchHeaderName }}
            - "--host-match-on-header"
            - {{ .Values.hostMatchHeaderName | quote }}
            {{- end }}
            {{- if .Values.databaseCache.enabled }}
            - "--enable-cache"
            {{- if .Values.databaseCache.ttl }}
            - "--cache-ttl-seconds"
            - {{ .Values.databaseCache.ttl | quote }}
            {{- end }}
            {{- if .Values.databaseCache.directory }}
            - "--cache-dir"
            - {{ .Values.databaseCache.directory | quote }}
            {{- end }}
            {{- end }}
            {{- if .Values.logLevel }}
            - "--log-level"
            - {{ .Values.logLevel | quote }}
            {{- end }}
            {{- if .Values.logFile }}
            - "--log-file"
            - {{ .Values.logFile | quote }}
            {{- end }}
            {{- range .Values.extraArgs }}
            - {{ . | quote }}
            {{- end }}
          {{- if .Values.extraEnv }}
          env:
            {{- toYaml .Values.extraEnv | trim | nindent 12 }}
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- if .Values.rbac.create }}
      serviceAccountName: {{ include "kubernetes-ingress-info.fullname" . }}
    {{- else }}
      serviceAccountName: {{ .Values.rbac.serviceAccountName | quote }}
    {{- end }}
