{{- if .Values.ingress.enabled }}
{{- $serviceName := include "kubernetes-ingress-info.fullname" . -}}
{{- $servicePort := .Values.service.port -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "kubernetes-ingress-info.fullname" . }}
  labels:
{{ include "kubernetes-ingress-info.labels" . | indent 4 }}
{{- if .Values.ingress.labels -}}
{{- with .Values.ingress.labels }}
  {{- toYaml . | trim | nindent 4 }}
{{- end }}
{{- end }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | trim | nindent 4 }}
  {{- end }}
spec:
  rules:
    - host: {{ .Values.ingress.host.name | quote }}
      http:
        paths:
          - backend:
              service:
                name: {{ $serviceName }}
                port:
                  number: {{ $servicePort }}
            path: {{ default "/" .Values.ingress.host.path | quote }}
            pathType: {{ .Values.ingress.host.pathType }}
  {{- if .Values.ingress.host.tls }}
  tls:
    - hosts:
        - {{ .Values.ingress.host.name }}
      secretName: {{ .Values.ingress.host.tlsSecret }}
  {{- end }}
{{- end }}
