{{- if .Values.rbac.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "kubernetes-ingress-info.fullname" . }}
  labels:
{{ include "kubernetes-ingress-info.labels" . | indent 4 }}
{{- end }}
